stages: 
 - build
# - deploy

build_job: 
 stage: build
 script: 
 # - echo "删除服务器上一次拉取的项目"
 # - rm -rf /root/gitlab/ 
 # - echo "删除nginx配置文件夹中，上一次的dist文件"
 # - rm -rf /etc/nginx/html/dist
  - echo "拉取代码"
  - cd /root/gitlab/project/
  - git clone http://10.1.8.174/tongyijiankong/web.git
  #- echo "使用npm下载依赖"
  #- cd /data/wwwroot/runner-1/OTO-vue
  #- npm install   --registry=https://registry.npm.taobao.org  
  #    --disturl=https://npm.taobao.org/dist 
  #    --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
 # - echo "使用npm编译打包项目"
 ## - npm run build
 # - echo "-----------------------------项目编译打包完成-----------------------------"
 only:
  - master
 tags: 
  - dev-web
  
