stages: 
 - build
 - deploy

build_job: 
 stage: build
 script: 
  - echo "删除服务器上一次拉取的项目"
  - rm -rf /root/gitlab/project/web 
  - echo "删除nginx配置文件夹中，上一次的dist文件"
  - cp -R /etc/nginx/html /root/gitlab/project
  - echo "拉取代码"
  - cd /root/gitlab/project/
  - git clone http://10.1.8.174/tongyijiankong/web.git
  - echo "项目下载成功"
  - echo "使用npm下载依赖"
  - cd /root/gitlab/project/web
  - cnpm install
  #- npm install --registry=https://registry.npm.taobao.org  
  #    --disturl=https://npm.taobao.org/dist 
  #    --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
  - echo "使用cnpm编译打包项目"
  - cnpm run build
  - echo "-----------------------------项目编译打包完成-----------------------------"
 only:
  - master
 tags: 
  - dev-web
  
deploy_job: 
 stage: deploy
 script: 
  - rm -rf /etc/nginx/html
  - echo "将打包完成后的dist文件复制到Nginx文件下"
  - cp -r /root/gitlab/project/web/dist /etc/nginx/html
  - echo "重启nginx服务"
  - systemctl restart nginx
  - echo "----------------------------------部署完成-------------------------------"
 
 only: 
  - master
 tags: 
  - dev-web

  
